# Generated by Django 6.0.6 on 2026-06-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='quiz_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='user_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
