# Generated by Django 4.1.3 on 2026-08-03 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_studentprofile_matric_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(default='objective', max_length=50)),
                ('questions', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_cache', to='api.document')),
            ],
            options={
                'unique_together': {('document', 'quiz_type')},
            },
        ),
    ]
